"""Add Career, Subject and LeapCareer models

Revision ID: 808622f20a9d
Revises: b6c3945f0913
Create Date: 2023-10-08 23:14:51.615326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '808622f20a9d'
down_revision: Union[str, None] = 'b6c3945f0913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_careers_id'), 'careers', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('leads_careers',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('lead_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('career_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id', 'lead_id', 'career_id')
    )
    op.create_index(op.f('ix_leads_careers_career_id'), 'leads_careers', ['career_id'], unique=False)
    op.create_index(op.f('ix_leads_careers_id'), 'leads_careers', ['id'], unique=False)
    op.create_index(op.f('ix_leads_careers_lead_id'), 'leads_careers', ['lead_id'], unique=False)
    op.create_table('subjects',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('career_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.PrimaryKeyConstraint('id', 'career_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subjects_career_id'), 'subjects', ['career_id'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.drop_index('ix_subject_career_id', table_name='subject')
    op.drop_index('ix_subject_id', table_name='subject')
    op.drop_table('subject')
    op.drop_index('ix_leadcareer_career_id', table_name='leadcareer')
    op.drop_index('ix_leadcareer_id', table_name='leadcareer')
    op.drop_index('ix_leadcareer_lead_id', table_name='leadcareer')
    op.drop_table('leadcareer')
    op.drop_index('ix_career_id', table_name='career')
    op.drop_table('career')
    op.drop_index('ix_lead_id', table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lead_pkey'),
    sa.UniqueConstraint('email', name='lead_email_key'),
    sa.UniqueConstraint('username', name='lead_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_lead_id', 'lead', ['id'], unique=False)
    op.create_table('career',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='career_pkey'),
    sa.UniqueConstraint('name', name='career_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_career_id', 'career', ['id'], unique=False)
    op.create_table('leadcareer',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('lead_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('career_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career.id'], name='leadcareer_career_id_fkey'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name='leadcareer_lead_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'lead_id', 'career_id', name='leadcareer_pkey')
    )
    op.create_index('ix_leadcareer_lead_id', 'leadcareer', ['lead_id'], unique=False)
    op.create_index('ix_leadcareer_id', 'leadcareer', ['id'], unique=False)
    op.create_index('ix_leadcareer_career_id', 'leadcareer', ['career_id'], unique=False)
    op.create_table('subject',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('career_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['career.id'], name='subject_career_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'career_id', name='subject_pkey'),
    sa.UniqueConstraint('name', name='subject_name_key')
    )
    op.create_index('ix_subject_id', 'subject', ['id'], unique=False)
    op.create_index('ix_subject_career_id', 'subject', ['career_id'], unique=False)
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_career_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_leads_careers_lead_id'), table_name='leads_careers')
    op.drop_index(op.f('ix_leads_careers_id'), table_name='leads_careers')
    op.drop_index(op.f('ix_leads_careers_career_id'), table_name='leads_careers')
    op.drop_table('leads_careers')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_careers_id'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###
